name: Package - All

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  linux:
    uses: dxx-redux/dxx-redux/.github/workflows/package-linux.yml@main
  windows:
    uses: dxx-redux/dxx-redux/.github/workflows/package-windows.yml@main
  msvc:
    uses: dxx-redux/dxx-redux/.github/workflows/package-msvc.yml@main
  macos:
    uses: dxx-redux/dxx-redux/.github/workflows/package-macos.yml@main
  macos-arm:
    uses: dxx-redux/dxx-redux/.github/workflows/package-macos-arm.yml@main

  release:
    name: GitHub Release
    runs-on: ubuntu-22.04
    needs: [linux, windows, msvc, macos, macos-arm]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
